version: "3.8"
services:
  web:
    depends_on:
      - db
    build: klausur-service
    environment:
      - DB_URI=mongodb://db:27017
    ports:
    - "80:3000"
  db:
    image: mongo:4.4.11-rc1
    volumes:
      - ./db_volume:/data/db

# nginx mit ssl evtl.
# micro-service
# network
