# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Klausur Service Unit Test CI

on: [push, pull_request]

jobs:
  run-unit-test:
    name: Klausur Service Unit Test
    runs-on: ubuntu-latest
    
    defaults:
      run:
        working-directory: ./klausur-service

    steps:
    - uses: actions/checkout@v2
    - name: Test using Node.js
      uses: actions/setup-node@v1
      with:
        node-version: '17'
    - name: Setup tests
      run: npm ci
    - name: Run test
      run: npm test
